//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace phaBalloting.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AttributesType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AttributesType()
        {
            this.ProjectTypeConfigurations = new HashSet<ProjectTypeConfiguration>();
            this.ProjectUnitAttributes = new HashSet<ProjectUnitAttribute>();
        }
    
        public int Id { get; set; }
        public string AttributeName { get; set; }
        public string Description { get; set; }
        public int DataTypeId { get; set; }
        public string UserId { get; set; }
        public System.DateTime EntryDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual AttributeDataType AttributeDataType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectTypeConfiguration> ProjectTypeConfigurations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectUnitAttribute> ProjectUnitAttributes { get; set; }
    }
}
