//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace phaBalloting.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Authentication
    {
        public int Id { get; set; }
        public string RoleId { get; set; }
        public int FormId { get; set; }
        public Nullable<bool> ViewRecords { get; set; }
        public Nullable<bool> EditRecords { get; set; }
        public Nullable<bool> DeleteRecords { get; set; }
        public Nullable<bool> AddRecords { get; set; }
    
        public virtual AppForm AppForm { get; set; }
        public virtual AspNetRole AspNetRole { get; set; }
    }
}
