//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace phaBalloting.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Balloting
    {
        public int Id { get; set; }
        public int MemberID { get; set; }
        public int ProjectUnitID { get; set; }
        public int EventID { get; set; }
    
        public virtual Event Event { get; set; }
        public virtual Member Member { get; set; }
        public virtual PojectUnit PojectUnit { get; set; }
    }
}
