//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace phaBalloting.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Balloting
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Balloting()
        {
            this.CancelledBallotings = new HashSet<CancelledBalloting>();
        }
    
        public int Id { get; set; }
        public int MemberID { get; set; }
        public int ProjectUnitID { get; set; }
        public int EventID { get; set; }
    
        public virtual Member Member { get; set; }
        public virtual PojectUnit PojectUnit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CancelledBalloting> CancelledBallotings { get; set; }
        public virtual Event Event { get; set; }
    }
}
