//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace phaBalloting.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class BPSGroup
    {
        public int Id { get; set; }
        public string BPSGroup1 { get; set; }
        public string Description { get; set; }
    }
}
