//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace phaBalloting.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class phaEntities : DbContext
    {
        public phaEntities()
            : base("name=phaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AppForm> AppForms { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AttributeDataType> AttributeDataTypes { get; set; }
        public virtual DbSet<AttributesType> AttributesTypes { get; set; }
        public virtual DbSet<Authentication> Authentications { get; set; }
        public virtual DbSet<Balloting> Ballotings { get; set; }
        public virtual DbSet<BPSGroup> BPSGroups { get; set; }
        public virtual DbSet<BPSList> BPSLists { get; set; }
        public virtual DbSet<BPSProject> BPSProjects { get; set; }
        public virtual DbSet<Event> Events { get; set; }
        public virtual DbSet<Member> Members { get; set; }
        public virtual DbSet<phaConfiguration> phaConfigurations { get; set; }
        public virtual DbSet<PojectUnit> PojectUnits { get; set; }
        public virtual DbSet<Project> Projects { get; set; }
        public virtual DbSet<ProjectTypeConfiguration> ProjectTypeConfigurations { get; set; }
        public virtual DbSet<ProjectType> ProjectTypes { get; set; }
        public virtual DbSet<ProjectUnitAttribute> ProjectUnitAttributes { get; set; }
        public virtual DbSet<UserActivity> UserActivities { get; set; }
        public virtual DbSet<UserProfile> UserProfiles { get; set; }
        public virtual DbSet<WaitingMember> WaitingMembers { get; set; }
    }
}
