//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace phaBalloting.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectUnitAttribute
    {
        public int Id { get; set; }
        public int UnitId { get; set; }
        public int AttributeId { get; set; }
        public string AttributeValue { get; set; }
        public string UserId { get; set; }
        public System.DateTime EntryDate { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string ModifiedBy { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual AttributesType AttributesType { get; set; }
        public virtual PojectUnit PojectUnit { get; set; }
    }
}
